# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------
QT    += core gui charts 
TEMPLATE = app
TARGET = volunteerManagementSystem
DESTDIR = ./x64/Debug
CONFIG += debug
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
include(volunteerManagementSystem.pri)
win32:RC_FILE = volunteerManagementSystem.rc
